### ISSUE TITLE
Issue with types for probeForRoute, decodePaymentRequest and getFeeRates

### ISSUE THREAD

**Issue by niteshbalusu11** [alexbosworth/lightning#115]
The types of routes in `probeForRoute` args does not match result of `decodePaymentRequest` so we cannot pass values from decodePaymentRequest to probeForRoute directly without type converstion, typescript will fail to compile.

https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/probe_for_route.d.ts#L49
https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/decode_payment_request.d.ts#L40

Also `tokens` seems to be optional if you pass `mtokens` in the actual code validate function, but it is a required type.

https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/probe_for_route.d.ts#L64
https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/probe_for_route.js#L108

getFeeRates is missing fee_rate in the result.
https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/get_fee_rates.d.ts#L4

**Comment by alexbosworth** [comment]
ping @bkiac

**Comment by bkiac** [comment]
I fixed the last two issues in #119, but the first one seems to be correct based on the docs:

`decodePaymentRequest` returns a string `base_fee_mtokens`:
https://github.com/alexbosworth/lightning/blob/5bc3a9e952e6a93cf672333829eb9c42f9e40a69/lnd_methods/offchain/decode_payment_request.js#L39

but `probeForRoute` accepts a number input for `base_fee_mtokens`:
https://github.com/alexbosworth/lightning/blob/5bc3a9e952e6a93cf672333829eb9c42f9e40a69/lnd_methods/offchain/probe_for_route.js#L50

@alexbosworth, is this an error in documentation, if so which is the correct type here? number or string, (or both valid)?

**Comment by alexbosworth** [comment]
It's string, it's an error in documentation

**Comment by bkiac** [comment]
Thanks, I'll update the docs and types in the PR

**Comment by alexbosworth** [comment]
I think I updated it in the comments on master
