### ISSUE TITLE
[Help] tor support

### ISSUE THREAD

**Issue by sidahmedabdelillah** [alexbosworth/lightning#130]
Does this library support connecting to lnd via .onion address ?

**Comment by sidahmedabdelillah** [comment]
I have just tested the implementation with a tor HTTP proxy. According to https://github.com/grpc/grpc-node/issues/992 grpc-js will take into consideration the  grpc_proxy and http_proxy environment variable so this library will work over tor network.

**Comment by alexbosworth** [comment]
great, maybe there is a way it can be made easier but thanks for this note
