### ISSUE TITLE
payments: getPayment (trackPayment) stuck 

### ISSUE THREAD

**Issue by dolcalmi** [alexbosworth/lightning#133]
somehow there is a payment in-flight without additional data and is causing getPayment getting stuck

```
$ lncli trackpayment 1c69f0...8f00ae
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
| HTLC_STATE | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE | TIMELOCK | CHAN_OUT | ROUTE |
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
Amount + fee:   0 + 0 sat
Payment hash:   1c69f0...8f00ae
Payment status: IN_FLIGHT
```
the getPayment code is https://github.com/GaloyMoney/galoy/blob/main/src/services/lnd/index.ts#L731

Possible solution: adding timeout to subscribeToPastPayment?

**Comment by alexbosworth** [comment]
I couldn't reproduce this behavior, I tried paying an invoice and holding it to avoid it completing, and when I did `getPayment` it returned a result

Do you have an isolated reproduction?

**Comment by dolcalmi** [comment]
seems to be an edge case, never got an empty (no amount, no route) response :thinking:

**Comment by alexbosworth** [comment]
ok that makes sense

so this payment is not actually pending, it's actually failed?

**Comment by dolcalmi** [comment]
according to pending htlcs in listchannels is not pending anymore but stil shows the same info
```
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
| HTLC_STATE | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE | TIMELOCK | CHAN_OUT | ROUTE |
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
Amount + fee:   0 + 0 sat
Payment hash:   1c69f0...8f00ae
Payment status: IN_FLIGHT
```

**Comment by alexbosworth** [comment]
I think this is an LND issue, it's not in flight so it shouldn't show it as such?

**Comment by dolcalmi** [comment]
closing because we updated to lnd 0.16... will reopen if it happens again
