### ISSUE TITLE
Typescript definition of subsribeToInvoices does not expect additional parameters

### ISSUE THREAD

**Issue by woofbotapp** [alexbosworth/lightning#134]
https://github.com/alexbosworth/lightning/blob/c5af24b75b88792cb17fa3b5aeb855f901b5f715/typescript/shared.d.ts#L46-L48

In addition to `lnd`, the function also accepts `added_after`, `confirmed_after`, `restart_delay_ms`.

Would be also nice to document what they mean - I don't understand what the "Index Number" in "Invoice Added After Index Number" is, and why would I need to set a "Restart Subscription Delay".

**Comment by alexbosworth** [comment]
Invoices have index numbers, you can see that in the invoice event

The subscription has auto restarting in it if it fails, you can mark how much it will wait before trying to start it up again
