### ISSUE TITLE
bun compatibility

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/lightning#148]
just gave a try to `bun` as a drop in replacement to `node` to see if that work on the Galoy stack, but it breaks with the lightning repo.

I got this error message: `[503,"FailedToConnectToDaemonToGetWalletStatus"]` when trying to execute `getWalletStatus`. 

haven't really dive into the issue yet more than encoutering this issue

**Comment by bkiac** [comment]
bun doesn't support HTTP/2 yet which is needed for the gRPC connection

https://github.com/oven-sh/bun/issues/887#issuecomment-1711967409

https://github.com/oven-sh/bun/issues/159

**Comment by nicolasburtey** [comment]
thanks for the comment @bkiac 

closing this for now, there is not much to do in this lib
