### ISSUE TITLE
Will be great to have here channelId filter as well

### ISSUE THREAD

**Issue by ybaidiuk** [alexbosworth/lightning#150]
https://github.com/alexbosworth/lightning/blob/063e18488377548c455d0485cf42a6914665b6b8/lnd_methods/offchain/get_forwards.d.ts#L9

**Comment by alexbosworth** [comment]
that isn't supported by LND so can't really deliver anything beyond client side filtering

**Comment by ybaidiuk** [comment]
Thanks for quick response.
