### ISSUE TITLE
Dependency of node 12?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/lightning#2]
Trying to update ln-service give me this error:

```
$ yarn upgrade ln-service
yarn upgrade v1.21.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning ln-service > is-hex@1.1.3: Development of this module has been stopped.
warning ln-service > lightning > is-hex@1.1.3: Development of this module has been stopped.
[3/5] 🚚  Fetching packages...
error lightning@1.2.1: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.16.3"
error Found incompatible module.
```

I'm running my code on the firebase function (ie: "serverless") which has not yet an engine for node 12 so I'm wondering if this is something that can be easily worked around

**Comment by alexbosworth** [comment]
Interesting, sure support for 10 could be added

**Comment by nicolasburtey** [comment]
yep, I see that it seems it has been removed recently, I guess to improve build time?

https://github.com/alexbosworth/lightning/commit/6bf5fcc1a49d2aa8fe8ca65b825baa162dbcfbad

would be great to have it back indeed :) keysend can't be used on node 10 :(

**Comment by nicolasburtey** [comment]
For information, the doc for firebase function:

https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version

Node 10 is still considered beta, so I would expect that it would take quite a bit of time before Node 12 is integrated.

**Comment by alexbosworth** [comment]
Should be changed to 10 now

**Comment by nicolasburtey** [comment]
it works. thanks! 🙏
