### ISSUE TITLE
mtokens as string?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/lightning#24]
is there a reason why there are attributes like [mtokens that are string](https://github.com/alexbosworth/lightning/blob/32b20d6474a926e2f092bbe9d4bc953ee27af7d4/lnd_methods/offchain/pay_via_payment_details.d.ts#L34)?

I have not checked as the grpc, and not sure how the definition has been created (manually or programmatically from the protobuf?)

**Comment by nicolasburtey** [comment]
why not using bigint (what is now in the standard, ie : `10n` )?

I think it's now supported by node v10+?

**Comment by alexbosworth** [comment]
You can do BigInt() on the attribute

I think it's just a style choice there is no reason BigInt couldn't be returned

I experimented with returning BigInt before but it didn't feel great in practice, and BigInt methods caused issues with browserify

**Comment by nicolasburtey** [comment]
ok thanks. closing this now.
