### ISSUE TITLE
Two events with differing data fired

### ISSUE THREAD

**Issue by krtk6160** [alexbosworth/lightning#26]
I am using `subscribeToForwards` to monitor forwards through my node and record the fee earned for accounting purposes.
While testing out on regtest, I found that each forward was generating two events, and both contained slightly different data.

```
{
  forward: {
    at: '2021-04-01T18:41:33.333Z',
    cltv_delta: 60,
    external_failure: undefined,
    fee: 1,
    fee_mtokens: '1000',
    in_channel: '454x1x0',
    in_payment: 1,
    internal_failure: undefined,
    is_confirmed: false,
    is_failed: false,
    is_receive: false,
    is_send: false,
    mtokens: '20000',
    out_channel: '555x1x0',
    out_payment: 1,
    timeout: 623,
    tokens: 20
  }
}
{
  forward: {
    at: '2021-04-01T18:41:33.436Z',
    cltv_delta: undefined,
    external_failure: undefined,
    fee: undefined,
    fee_mtokens: undefined,
    in_channel: '454x1x0',
    in_payment: 1,
    internal_failure: undefined,
    is_confirmed: true,
    is_failed: false,
    is_receive: false,
    is_send: false,
    mtokens: undefined,
    out_channel: '555x1x0',
    out_payment: 1,
    timeout: undefined,
    tokens: undefined
  }
}
```

As can be seen, the first event has the fee related info that I want, but the `is_confirmed` field is `false`, hence I do not want to use this data. I want to use the data (`fee_mtokens` specifically) from the event where the `is_confirmed` is `true`. However, all the forwards result in these two objects where in the second object, the `is_confirmed` is `true` but the fee data is `undefined`.

**Comment by alexbosworth** [comment]
You can hold on to the first event and then combine it with the second event?

**Comment by alexbosworth** [comment]
Another option is to request the forwards using getForwards whenever an event is fired

**Comment by krtk6160** [comment]
> You can hold on to the first event and then combine it with the second event?

Yes I could do that, but it seems like a hacky approach. Why is it that the second event does not contain the fee data?

Also, I would be more comfortable using this approach if there was some sort of unique id shared between those two objects that could identify that they're from the same payment. But no such field exists. In that case there could be issues when multiple forwards went through within a short span of time.

> Another option is to request the forwards using getForwards whenever an event is fired

Same for this. Due to the absence of a unique identifier, I cannot say with confidence whether the fee for a particular forward was already accounted for or not (in case of multiple forwards within a short span of time).

**Comment by alexbosworth** [comment]
> > You can hold on to the first event and then combine it with the second event?
> 
> Yes I could do that, but it seems like a hacky approach. Why is it that the second event does not contain the fee data?

This is an LND issue, it doesn't contain this data

> 
> Also, I would be more comfortable using this approach if there was some sort of unique id shared between those two objects that could identify that they're from the same payment. But no such field exists. In that case there could be issues when multiple forwards went through within a short span of time.
> 
> > Another option is to request the forwards using getForwards whenever an event is fired
> 
> Same for this. Due to the absence of a unique identifier, I cannot say with confidence whether the fee for a particular forward was already accounted for or not (in case of multiple forwards within a short span of time).

Yes, this identifier is absent in LND so again, an LND issue

**Comment by krtk6160** [comment]
Okay I will create an issue there.

**Comment by krtk6160** [comment]
@alexbosworth Is the duplicate event also an LND issue?

**Comment by alexbosworth** [comment]
Yes LND requires that you maintain the state between the two events
