### ISSUE TITLE
reconnect to a restarted lnd

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/lightning#27]
I have a long lived node that is fetching the online status of a lnd. 
if lnd restarts, trying to connect back to it using the saved `{lnd}` I have doesn't work: 
```
    err: [
      503,
      "FailedToConnectToDaemon"
    ]
```
but even if I try to recreated the lnd object, I still have the same issue. any idea what could be wrong?

**Comment by nicolasburtey** [comment]
the code is here if this can help: https://github.com/GaloyMoney/galoy/blob/a4f1241768407b77a4ffc4388891c3312bffda8e/src/lndConfig.ts

**Comment by alexbosworth** [comment]
On a restart you do need a new lnd object the old one has to be tossed

The APIs aren't available right away and there is no API to tell you if the APIs are ready so you have to spin on the error until you don't get an error

**Comment by nicolasburtey** [comment]
> On a restart you do need a new lnd object the old one has to be tossed
> 
> The APIs aren't available right away and there is no API to tell you if the APIs are ready so you have to spin on the error until you don't get an error

ok I have been regenerating the lnd object and still could not reconnect back. I'll double check I'm doing it right. 

> The APIs aren't available right away and there is no API to tell you if the APIs are ready so you have to spin on the error until you don't get an error

the call rely on some promise? (it seems the function is synchronous)

it would be milliseconds I guess? have been waiting 30 seconds and was still failing.

**Comment by alexbosworth** [comment]
It depends on your setup I guess

You can see in the integration test how I figure out if LND is ready: https://github.com/alexbosworth/ln-service/blob/master/test/macros/spawn_lnd.js#L457 - basically I just retry a call until it doesn't error

**Comment by nicolasburtey** [comment]
do you have a test when you are trying to reconnect from a lnd after a crash/restart?

here is a quick script to reproduce the issue:

```
it('reconnect', async () => {
  while (true) {
    const {lnd} = authenticatedLndGrpc(input)
    try {
      await getWalletInfo({ lnd })
      console.log("ok")
    } catch (err) {
      console.log("nok")
    }
    await sleep(1000)
  }
}, 300000)
```

and I just restart the node while the script is running. 

it's like if there were some state on the grpc side that would prevent a reconnection. (although grpc is stateless from what I know? don't know a lot about grpc)

**Comment by alexbosworth** [comment]
here is one where it is stopped and started : https://github.com/alexbosworth/ln-service/blob/master/test/macros/change_password.js

yeah if things are happening from scratch then the new grpc shouldn't have anything from the old grpc

I also have a restarting script here that can survive an lnd being stopped and restarted: https://github.com/alexbosworth/balanceofsatoshis/blob/master/telegram/connect_to_telegram.js#L89

**Comment by nicolasburtey** [comment]
I had a config issue on my devnet that would not keep the db on a lnd restart. so lnd would generate new key after restart
