### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by bkiac** [alexbosworth/lightning#35]
`lnd_methods` are fully typed now, what other modules/methods are you planning to export that still need types? Since the project isn't written in TypeScript creating types for internal methods is unnecessary.

**Comment by alexbosworth** [comment]
Cool, yeah the internal methods probably don't need typescript

I still don't use typescript myself anywhere yet so I don't really know where it would be useful

**Comment by bkiac** [comment]
I think any method that you expect consumers of this package would use should be typed, the `lnd_methods` module is obvious but I'm not sure if you were planning to expose any other functions in `index.js`

**Comment by alexbosworth** [comment]
I think that's all there is for the moment, until LND adds more methods or I fill in some existing gaps

Currently I'm feeling like I need to do a big restructuring project before moving forward with a lot of new functionality, generally I want to split up this library a bit so it is faster to load and faster to test. It currently takes 2-3 minutes on my machine to run all the tests and test coverage and I'd like that to complete in like 30 seconds.

I've also started on a break out project which is to provide unit test mocking for users of these methods: https://github.com/alexbosworth/mock-lnd

The idea of that is that if you are creating an application you can more easily write a unit test against using these lightning methods

**Comment by bkiac** [comment]
Okay, I think I close this for now then; I will try to add types for any new LND method if you add any

**Comment by alexbosworth** [comment]
I added a new method `subscribeToPastPayments`, this will notify on settled payments in a future version of LND
