### ISSUE TITLE
GetTowerServerInfo is missing its types

### ISSUE THREAD

**Issue by otaviobps** [alexbosworth/lightning#37]
The interfaces are not implemented and this method is not being exported. I forked the repo and I'm fixing it

**Comment by otaviobps** [comment]
I'm closing because I'm running an outdated version. Just checked it and the method is implemented

**Comment by otaviobps** [comment]
@alexbosworth can you check the published NPM version? It is actually missing the `get_tower_server_info.d.ts` declaration file, but it's present here in the repo

**Comment by alexbosworth** [comment]
maybe @bkiac would know, I don't really know how it is supposed to be setup

**Comment by bkiac** [comment]
I checked with `lightning@4.4.0` and `typescript@4.4.3`, it seems to work for me. Imports are valid and the declaration files are present in `node_modules`.
