### ISSUE TITLE
getPayment and getPayments should return the same payment details

### ISSUE THREAD

**Issue by dolcalmi** [alexbosworth/lightning#39]
currently getPayment has some missing attributes (like creation date)

### Related info
TrackPaymentV2: https://api.lightning.community/#trackpaymentv2
ListPayments: https://api.lightning.community/#listpayments

**Comment by alexbosworth** [comment]
anything other than creation date you particularly want?

**Comment by dolcalmi** [comment]
we use date for support cases but should return the same data, maybe use `rpc_payment_as_payment` in `getPayment` too. If you like a can do the PR

**Comment by alexbosworth** [comment]
ok I can take a look at this in a bit

**Comment by alexbosworth** [comment]
I put up the creation date and the original request, is that what you are looking for?
