### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/lightning#4]
Some context first:

I'm thinking of switching from lnService in favor or a more lightweight library on the server-side. The goal is to unify the API; as on the wallet-side I'm currently mostly using GRPC directly. Because lnService heavily changes variable name/ has specific ways to interpret GRPC responses, this is an overhead in the long run. 

I guess this is the goal of this library, but I'm not too sure. some examples would be great to understand this better.

**Comment by alexbosworth** [comment]
Yeah this library will continue the renaming and result interpretations from ln-service

**Comment by nicolasburtey** [comment]
ok
