### ISSUE TITLE
`pending` array missing from `getPayment` method return

### ISSUE THREAD

**Issue by vindard** [alexbosworth/lightning#50]
For cases where the payment is pending, according to the [function's documentation](https://github.com/alexbosworth/lightning/blob/e948ebd7fca54a04b2b0d3715dd3bc9063aef57f/lnd_methods/offchain/get_payment.js#L20) we should see a ~`payment`~ `pending` property with an array of the payments. This is usually missing from the return from my testing so far:

```ts
// Object returned from `getPayment` when payment is pending
{
  failed: undefined,
  is_confirmed: false,
  is_failed: false,
  is_pending: true,
  payment: undefined
}

```

**Comment by alexbosworth** [comment]
the payment is for successful payments, you want the `pending` attribute, maybe you need to update?

**Comment by vindard** [comment]
Sorry I meant to say `pending` attribute... yes that attribute isn't there on the return when `is_pending` is `true`

Do I need to update something to get that?

**Comment by alexbosworth** [comment]
if it's failed then pending doesn't exist yeah, what are you looking for exactly?

**Comment by alexbosworth** [comment]
`pending` is new though yes, it was added in `4.14.0`

**Comment by vindard** [comment]
Ok thanks that was it! I was on `4.10.6` 🙈 

Tangential question, the `request` attribute within `payment` and `pending` always seems to come back as undefined. When should I expect this to be populated?

**Comment by alexbosworth** [comment]
`request` will only be populated if you are using `pay` or `payViaPaymentRequest` methods and passing the request to make the payment

**Comment by alexbosworth** [comment]
Also btw `pending` doesn't have types yet on the `subscribeToPastPayment` method, I added types to the `getPayment` method but I couldn't figure out how to add them to the subscription events, @bkiac maybe can help

**Comment by vindard** [comment]
> Also btw `pending` doesn't have types yet on the `subscribeToPastPayment` method, I added types to the `getPayment` method but I couldn't figure out how to add them to the subscription events, @bkiac maybe can help

Thanks for the heads up. I'm only using the `getPayment` types for now so that's not a problem

**Comment by vindard** [comment]
One more related question on this. Is there a way to see distinct payment attempts via this method for cases where a payment may have failed, and was then re-attempted and succeeded?

**Comment by alexbosworth** [comment]
If you want the attempts I think you could use the subscription API while you are paying, and then record the attempts as they are emitted

**Comment by bkiac** [comment]
> Also btw `pending` doesn't have types yet on the `subscribeToPastPayment` method, I added types to the `getPayment` method but I couldn't figure out how to add them to the subscription events, @bkiac maybe can help

I added the missing type in #51
You can't really type the events, I just create a type that matches the subscription + event name so the consumer can type the object explicitly
```ts
emitter.on("paying", (data: SubscribeToPastPaymentPayingEvent) => {...})
```

**Comment by alexbosworth** [comment]
I added in-flight events to pay via request and pay via details as well: routing failures and pending attempts
