### ISSUE TITLE
`paths` property on attempts in `GetPaymentsResult`

### ISSUE THREAD

**Issue by vindard** [alexbosworth/lightning#54]
## Description

We're looking at parsing/persisting payments data that we get back from this library in different ways and had a question about a new approach we're trying now.

We'd like to use the `getPayments` method to get info about distinct attempts related to a single payment (hash?). We noticed that for the `getPayment` method in its `getPaymentResult` object there is a `paths` property under the `pending`/`payment` property that would contain all the paths that a payment would take in the case of an MPP payment being done. Ideally we'd like to get this info from the `getPayments` call as well but we're not sure how this would be reflected within the `attempts` array in the `GetPaymentsResult` object.

Can there be more than one successful attempt in the `attempts` array in the case of an MPP attempt where parts of the MPP can succeed but the entire thing fails?

---

This was hard to phrase as a question, please do ask for clarification on any part of this that is unclear 😅 

_Tagging @jireva as well as the co-author of this_

**Comment by alexbosworth** [comment]
In the `paths` array it should reflect the multiple paths yeah

You can try a test of this here: https://github.com/alexbosworth/ln-service/blob/master/test/routerrpc-integration/test_multipath_payment.js and that will generate a MPP payment in regtest

**Comment by vindard** [comment]
Ok great thanks, will check that out and get back to you if we have any other questions

**Comment by vindard** [comment]
The test was a great guide for what we needed to trigger an MPP payment, thanks! Closing this now
