### ISSUE TITLE
Add getPendingPayments or allow to pass include_incomplete

### ISSUE THREAD

**Issue by dolcalmi** [alexbosworth/lightning#61]
Trying to create a fallback for this https://github.com/lightningnetwork/lnd/issues/6249 we found that there is no way to get pending payments (and now we know that we can't trust in trackpayment response).

Do you prefer getPendingPayments or include include_incomplete in getPayments?

Let us know what you prefer to push a PR

thanks in advance

ps: also would be useful get the raw status https://github.com/alexbosworth/lightning/blob/master/lnd_responses/rpc_payment_as_payment.js#L206 because we delete failed attemps so is not possible to compare against track payment

**Comment by alexbosworth** [comment]
getPendingPayments would be cool sure

**Comment by alexbosworth** [comment]
Will the response of this API be different from trackpayment?

**Comment by vindard** [comment]
I think the idea is to use the `listPayments` api instead

**Comment by dolcalmi** [comment]
> Will the response of this API be different from trackpayment?

it will be similar to getFailedPayments, should use https://github.com/alexbosworth/lightning/blob/master/lnd_responses/rpc_payment_as_payment.js

**Comment by alexbosworth** [comment]
OK that makes sense, yeah this could be an interesting addition to see what payments are in flight

I'm curious if there is a difference between the result of listpayment for pending and getchannels => map htlc hashes to track payment results
