### ISSUE TITLE
[Question] Is there any way to terminate a subscription for the client side?

### ISSUE THREAD

**Issue by vindard** [alexbosworth/lightning#79]
I'm working with the `subscribeToInvoices` method in some tests and am trying to figure out if there's a way to explicitly end the subscription when I'm done with using it.

**Comment by alexbosworth** [comment]
remove listeners

**Comment by alexbosworth** [comment]
ok i guess this should be added but isn't added

**Comment by alexbosworth** [comment]
should be addressed in 5.16.5

**Comment by vindard** [comment]
I'll test this tomorrow on our codebase to confirm

**Comment by vindard** [comment]
> should be addressed in 5.16.5

The subscription was being canceled correctly now but the `doUntil` loop was still being left open. I added some code with one approach to addressing this that now works for our use-case.

PR: https://github.com/alexbosworth/lightning/pull/80

**Comment by alexbosworth** [comment]
Ah interesting ok

**Comment by vindard** [comment]
Closing this now, all sorted on our end. Thanks!
