### ISSUE TITLE
Typescript for schnorr signing

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/lightning#82]
5.18.0 adds `type` to signBytes arguments

`type` is a string that can be `ecdsa` or `schnorr`

This can be updated in typescript definitions, ping @bkiac

**Comment by bkiac** [comment]
I'll fix it and #81 this week

**Comment by alexbosworth** [comment]
Cool, also there is:

closeChannel: max_tokens_per_vbyte - Fee rate number
getChainTransactions, subscribeToTransactions: inputs array of tx id hex string and vout number, plus is local bool
