### ISSUE TITLE
Not possible to pay sub-satoshi amount to zero-amount invoice

### ISSUE THREAD

**Issue by vindard** [alexbosworth/lightning#87]
This works:
- `pay({ lnd, request: invoice, mtokens: "1995" })`

This errors with `PaymentPathfindingFailedToFindPossibleRoute`:
- `pay({ lnd, request: invoice, mtokens: "995" })`

Is this a feature or bug? 😅

**Comment by alexbosworth** [comment]
Maybe there is no route?

**Comment by vindard** [comment]
> Maybe there is no route?

More context:
- This is in regtest with a channel between 2 local test nodes
- I've set `bitcoin.minhtlc=1` in `lnd.conf` for both nodes
- The payment for `995` msats fails with that error
- A subsequent payment on the same no-amount invoice for `1995` msats succeeds

I'm not sure if you have any ideas what might be causing this (it may not be specific to this library I guess)

**Comment by alexbosworth** [comment]
Can you lookup the channel to see the policies?

**Comment by alexbosworth** [comment]
Did you also set bitcoin.minhtlcout= ?

**Comment by vindard** [comment]
> Did you also set bitcoin.minhtlcout= ?

Missed that one. This fixed it, thanks!
